server:
  port: 8080

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_service_db
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.order_by.default_null_ordering: last
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka